import fs from "fs-extra";
import path from "path";
import { getPackageDistPaths, getPackages } from "./utils";

async function writeGeneratedIgnoreFile(filename: string, contents: string) {
	const header = "# WARNING: This file is automatically generated";
	await fs.writeFile(filename, header + "\n" + contents + "\n");
}

export async function generateIgnoreFiles() {
	const packages = await getPackages();
	for (const pkg of packages) {
		const entries: string[] = [];
		for (const entrypointPath of getPackageDistPaths(pkg)) {
			const basename = path.basename(entrypointPath);
			if (basename !== "index") {
				entries.push("/" + basename);
			}
		}
		writeGeneratedIgnoreFile(
			path.join(pkg.rootPath, ".gitignore"),
			entries.join("\n")
		);
		writeGeneratedIgnoreFile(
			path.join(pkg.rootPath, ".npmignore"),
			entries.map((entry) => "!" + entry).join("\n")
		);
	}
}

generateIgnoreFiles();
